/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const FriendsLazyImport = createFileRoute('/friends')()
const CardsLazyImport = createFileRoute('/cards')()
const IndexLazyImport = createFileRoute('/')()
const SavingsIndexLazyImport = createFileRoute('/savings/')()
const SavingsIdLazyImport = createFileRoute('/savings/$id')()
const AuthRegisterLazyImport = createFileRoute('/auth/register')()
const AuthLogoutLazyImport = createFileRoute('/auth/logout')()
const AuthLoginLazyImport = createFileRoute('/auth/login')()

// Create/Update Routes

const FriendsLazyRoute = FriendsLazyImport.update({
  path: '/friends',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/friends.lazy').then((d) => d.Route))

const CardsLazyRoute = CardsLazyImport.update({
  path: '/cards',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cards.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SavingsIndexLazyRoute = SavingsIndexLazyImport.update({
  path: '/savings/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/savings/index.lazy').then((d) => d.Route))

const SavingsIdLazyRoute = SavingsIdLazyImport.update({
  path: '/savings/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/savings/$id.lazy').then((d) => d.Route))

const AuthRegisterLazyRoute = AuthRegisterLazyImport.update({
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/register.lazy').then((d) => d.Route))

const AuthLogoutLazyRoute = AuthLogoutLazyImport.update({
  path: '/auth/logout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/logout.lazy').then((d) => d.Route))

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsLazyImport
      parentRoute: typeof rootRoute
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/savings/$id': {
      id: '/savings/$id'
      path: '/savings/$id'
      fullPath: '/savings/$id'
      preLoaderRoute: typeof SavingsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/savings/': {
      id: '/savings/'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CardsLazyRoute,
  FriendsLazyRoute,
  AuthLoginLazyRoute,
  AuthLogoutLazyRoute,
  AuthRegisterLazyRoute,
  SavingsIdLazyRoute,
  SavingsIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cards",
        "/friends",
        "/auth/login",
        "/auth/logout",
        "/auth/register",
        "/savings/$id",
        "/savings/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cards": {
      "filePath": "cards.lazy.tsx"
    },
    "/friends": {
      "filePath": "friends.lazy.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.lazy.tsx"
    },
    "/auth/logout": {
      "filePath": "auth/logout.lazy.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.lazy.tsx"
    },
    "/savings/$id": {
      "filePath": "savings/$id.lazy.tsx"
    },
    "/savings/": {
      "filePath": "savings/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
